### ISSUE TITLE
Add template for Pull Request

### ISSUE THREAD

**Issue by salazarsebas** [Crypto-Jaguars/Revolutionary_Farmers#1]
## The template must have the following parts:

- Title: Pull Request Overview
- Summary
- Changes Made
- Tests Results
- Next Steps

Use this as an example:

# Pull Request Overview

## 📝 Summary
Provide a brief overview of what this PR accomplishes.

## 🪧 Related Issues
- Closes #(issue)

## 🛠️ Type of Change
Mark with an x all the checkboxes that apply (like [x]).

- [ ] 📝 Documentation (updates to README, docs, or comments)
- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] 👌 Enhancement (non-breaking change which adds functionality)
- [ ] 💥 Breaking change (fix or feature that would cause existing functionality to change)

## 🔄 Changes Made
What's Changed
Provide a clear and concise description of what you changed and why.

## 🔧 Tests Results
Describe the tests you performed to verify your changes.

## 🔜 Next Steps
Indicate actions or improvements to be taken after this PR, if applicable.

**Comment by Michaelkingsdev** [comment]
hello @sasasamaes
Can i take on this issue? I have the required expertise to create a well standard and detailed markdown documentation. I will make PR in 24hrs. Thanks

**Comment by SYLVIANNORUKA** [comment]
Can I jump on this task?I am a Front-end and smart contract developer. I am proficient in tailwind css, Next Js, Typescript, JavaScript, Cairo and Rust. I would love to contribute to this project.

**Comment by nov0ax** [comment]
I'd like to take this issue. I've worked on similar issues in the past and have a pretty clear idea how to takle this issue, already have a nice template that can help the team to have this ready today.
#dojocodingCR

**Comment by Akshola00** [comment]
Is this issue still available?

**Comment by pheobeayo** [comment]
May I handle this issue?

I am a Web3 front-end developer skilled in technical documentation and software development. I greatly understand technologies like JavaScript, Typescript, Cairo, Rust and Solidity. I have contributed successfully to open-source projects like Stark Quest and Speedrun scaffold-stark.
My Approach includes:
- Write a well-structured template containing the needed information using the correct references for a PR templates outlining the parts needed as instructed.
- Create a Pull Request (PR)
- Request for a Review
- Make changes based on the Review of the PR.

**Comment by Benjtalkshow** [comment]
Could I try solving this?

**Comment by nanoulloa** [comment]
I would like to have this issue, I am a software development engineer and it is my first time contributing to a project in onlydust and I would love to contribute to this project, despite my first project I have an idea for a template that could help the project a lot

**Comment by Iwueseiter** [comment]
Could I take a shot at this?

I'm a frontend/smart contract developer and a technical writer.
Here are links to comprehensive docs I've written and have been merged Flex-NFT-Marketplace/Flex-Marketplace-Contract#107, https://github.com/cairo-book/cairo-book/pull/1019, https://github.com/horuslabsio/tokenbound-contract-docs/pull/12, https://github.com/sivicstudio/starkludo/pull/102, https://hackmd.io/@-__sK8xkRjuXHkFZQLyYXg/HkLcMImM1l.

**Comment by SudiptaPaul-31** [comment]
Will love to work on this issue.

**Comment by ShantelPeters** [comment]
Can I handle this task?

**Comment by CollinsC1O** [comment]
I’d love to work on this task.

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev, techical writer and a blockchain dev kindly assign :)

**Comment by EmmanuelAR** [comment]
Can I contribute to this one? I will create the template, also im manteiner too so i have experience, Dojo coding member too!

**Comment by derianrddev** [comment]
Hello, my name is Derian Rodríguez. I am a passionate software engineer with over one year of experience, actively contributing to open-source projects through OnlyDust. My experience includes full-stack development with a focus on backend, frontend, and web3 development using Starknet and Cairo. Additionally, I am part of the Dojo Coding community. I would follow all the guidelines and instructions to get exactly what you want. I would love to contribute and support the development of this project.

**Comment by ManuelJG1999** [comment]
Hi @nov0ax 
Thank you for your enthusiasm in contributing to our project. 
Wishing you great success as you take on this task.

Any questions you may have, please let us know.
