### ISSUE TITLE
Implement Translations for Android App in Spanish

### ISSUE THREAD

**Issue by sasasamaes** [Crypto-Jaguars/Revolutionary_Farmers#10]
Add Spanish translations to the Android app to ensure it is fully localized for Spanish-speaking users.

**TASKS:**

## 1.	Translation File Setup:
	•	Create or update the strings.xml file in the res/values-es directory.
	•	Ensure all UI text, error messages, and button labels are translated into Spanish.
## 2.	UI Implementation:
	•	Verify that all elements, including notifications, tooltips, and dialog boxes, are properly localized.
	•	Ensure the app switches to the correct language based on user preference or device settings.
## 3.	Dynamic Content Handling:
	•	Ensure dynamic content like error messages, alerts, and pop-ups are also translated and updated accordingly.
## 4.	Testing:
	•	Test the app’s functionality with the Spanish language selected to confirm proper translations.
	•	Validate that the layout adapts correctly for Spanish text, especially in terms of text direction or length.
## 5.	Consistency Check:
	•	Review the app for any untranslated text or inconsistencies between languages.

## Expected Outcome:

The app should be fully translated into Spanish, providing a seamless user experience for Spanish-speaking users.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by Kom02** [comment]
Hi, My name is Kevin Obando, a full stack junior developer with 2 years of experience from Costa Rica. I am starting in this community and I want to help in this project.

**Comment by CristopherAguilar10** [comment]
Hi, Revolutionary Farmers team
I'm part of Dojo Coding. I've had the opportunity to contribute to the Bytebeast project at OnlyDust, and I'm currently Lead Developer of the Citizen of Arcanis project, an on-chain MMORPG we developed during the Starknet Hacker House 2024. I have experience in application development, with solid knowledge in Java, C#, .NET, and related technologies.
I am prepared to:
Configure the translation structure (strings.xml) to ensure that all application texts are adapted to Spanish.
Validate that interfaces and dynamic elements (errors, pop-up messages) are translated correctly.
Perform functional tests to ensure a smooth user experience in Spanish.
I find this project fascinating, and I would love to collaborate to expand its reach to new audiences.

**Comment by ShantelPeters** [comment]
Is it okay if I tackle this?

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev, techical writer and a blockchain dev kindly assign :)

**Comment by Kom02** [comment]
Hi, My name is Kevin Obando, a full stack junior developer with 2 years of experience from Costa Rica. I am starting in this community and I want to help in this project.
