### ISSUE TITLE
Implement Translations for Web App in Spanish and English

### ISSUE THREAD

**Issue by aguilar1x** [Crypto-Jaguars/Revolutionary_Farmers#12]
## Issue Description
Implement a robust internationalization solution for our Next.js application to support multiple languages and improve global user experience.

## Objectives
- Create a comprehensive internationalization strategy
- Implement language switching functionality
- Ensure seamless translation management
- Optimize performance for multilingual content

### 1. Translation Management
- Integrate a translation management system
- Support JSON-based translation files
- Implement dynamic language loading
- Create a centralized translation utility

### 2. Language Routing
- Configure language-based routing
- Implement language prefix for URLs (e.g., /en/page, /fr/page)
- Detect and set user's preferred language automatically
- Allow manual language selection

## Recommended Approach
1. Use Next.js built-in internationalization support or a library like next-i18next
2. Create separate translation files for each supported language
3. Implement language context/provider
4. Add language switcher component

## Proposed Libraries/Tools
- next-i18next
- react-intl
- i18next
- Custom translation management system

## **NOTE** 
A reference about the implementation button.

![image](https://github.com/user-attachments/assets/f7758824-2255-4645-884a-66a265350f9f)

## **FIGMA**
[FIGMA DESIGN](https://www.figma.com/design/okdNMG3dW4UFcKUSikrs6e/Revolutionary-Farmers?node-id=7-2&node-type=canvas&t=M2XbI5NKqSvBUI8P-0)

**Comment by emarc99** [comment]
Could I take over this issue?

I will install next-i18next, then enable i18n routing in configuration. I will create translation files, and wrap main content component with `appWithTranslation` to provide translation context throughout the app. Finally, handle Server Side rendering.

Run tests. Eta - 3hours

**Comment by Kingsuite** [comment]
I’d like to work on this.

**Comment by CristopherAguilar10** [comment]
Hi, Revolutionary Farmers team
I'm part of Dojo Coding. I've had the opportunity to contribute to the Bytebeast project at OnlyDust, and I'm currently Lead Developer of the Citizen of Arcanis project, an on-chain MMORPG we developed during the Starknet Hacker House 2024. I have experience in application development, with solid knowledge in Java, C#, .NET, and related technologies.
I am prepared to:
Configure the translation structure (strings.xml) to ensure that all application texts are adapted to Spanish.
Validate that interfaces and dynamic elements (errors, pop-up messages) are translated correctly.
Perform functional tests to ensure a smooth user experience in Spanish.
I find this project fascinating, and I would love to collaborate to expand its reach to new audiences.

**Comment by Ayoazeez26** [comment]
Mind if I try this one?
I have worked on a similar issue here https://github.com/horuslabsio/seamlessui/pull/19
I would make sure it works as expected following the requirements before submitting a PR
ETA - 4 days

**Comment by od-hunter** [comment]
I am a blockchain developer, and my experience includes html, css, react, javaScript, typescript, solidity and cairo.

Please assign me I’m ready to work.

**Comment by josephpdf** [comment]
Hi! @aguilar1x
I'm Joseph Poveda, I'm a member of the Dojo Coding community.
A bit about my background is that I'm just starting out with Only Dust and I want to contribute as much as I can to the project. My knowledge of different programming languages ​​will allow me to better solve problems.
To solve this issue I will:
1. **Develop an Internationalization Strategy:**
- Create a comprehensive plan for supporting multiple languages in the application.
2. **Implement Translation Management:**
- Integrate a translation management system.
- Use JSON-based translation files.
- Implement dynamic language loading.
- Create a centralized translation utility.
3. **Configure Language Routing:** 
- Set up language-based routing with URL prefixes (e.g., /en/page, /fr/page).
- Detect and set the user’s preferred language automatically.
- Allow manual language selection.
4. **Use Recommended Libraries/Tools:**
- Utilize Next.js built-in internationalization support or a library like next-i18next.
- Create separate translation files for each supported language.
- Implement a language context/provider.
- Add a language switcher component.
5. **Optimize Performance:**
- Ensure that the implementation is optimized for performance with multilingual content.

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev kindly assign :)

**Comment by ShantelPeters** [comment]
Could I grab this task?

**Comment by Awointa** [comment]
this task would be great opportunity to test my REACT skill under a short deadline
