### ISSUE TITLE
Implement a test library in Android

### ISSUE THREAD

**Issue by sasasamaes** [Crypto-Jaguars/Revolutionary_Farmers#26]
**Objective**
Integrate a robust testing library for Android.

**Recommended Option: Espresso + JUnit**
**Feel free to suggest another option**

1. Dependencies (build.gradle)
`dependencies {
    // JUnit
    testImplementation 'junit:junit:4.13.2'
    
    // Kotlin Test
    testImplementation 'org.jetbrains.kotlin:kotlin-test-junit:1.8.20'
    
    // Mockito
    testImplementation 'org.mockito:mockito-core:4.5.1'
    
    // Android Testing
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}`

**Test Structure**

Directory: src/test/kotlin
Directory: src/androidTest/kotlin

**Unit Test Example**

`class UserViewModelTest {
    @Test
    fun `test user login`() {
        val viewModel = UserViewModel()
        viewModel.login("user", "password")
        assertTrue(viewModel.isLoggedIn)
    }
}`

**Acceptance Criteria**

- [ ]  Configuring testing libraries
- [ ]  Unit tests implemented
- [ ]  UI Tests with Espresso
- [ ]  Integration with CI/CD

**Comment by mimisavage** [comment]
Could I take a shot at this?

**Comment by ooochoche** [comment]
Gm, I've gone through the description and I can implement a test library to meet the accepted criteria.

**Comment by aniruddhaaps** [comment]
To address this issue I would integrate Espresso and JUnit for unit and UI testing, with dependencies for JUnit, Kotlin Test, and Mockito already configured in build.gradle. Then implement a test under src/test/kotlin. Make sure this leads to having beautiful integration with CI/CD for seamless execution.

**Comment by evgongora** [comment]
Hey! Can I take this issue?
