### ISSUE TITLE
Add documentation section to the readme

### ISSUE THREAD

**Issue by salazarsebas** [Crypto-Jaguars/Revolutionary_Farmers#37]
## Description
Implement in the documentation a section to clarify that it must work in the dev branch, and that Pull Requests must be directed to the dev branch, not to the main branch.

**Comment by therealemino** [comment]
Mind if I take this issue?

**Comment by ShantelPeters** [comment]
May I handle this issue?

**Comment by Michaelkingsdev** [comment]
Can I try solving this issue?

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer with a strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Rust. I’ve made over 49 contributions to over 17 projects in the OnlyDust ecosystem, solving complex issues and delivering efficient, scalable solutions.

I can handle this task.
ETA is 3days.

**Comment by pablomadrigal** [comment]
## I'm Pablo Madrigal.
I'm a Fullstack Developer with more than 5 years of experience primary on React and Node.js and now learning web3, I'm also part of Dojo Coding ⛩️

## Problem
Add documentation section to the readme

## Solution
Modify the read me file to clarify that it must work in the dev branch, and that Pull Requests must be directed to the dev branch, not to the main branch.

I have experince create Github rules for PR's, they are mandatory only on paid susbcriptions, but at least it lead the way in how to create the PR's and merge code
