### ISSUE TITLE
Add an Issue Template to the Repository

### ISSUE THREAD

**Issue by sasasamaes** [Crypto-Jaguars/Revolutionary_Farmers#5]
## Create a standardized template to guide contributors in creating well-structured and detailed issues.

**The template should include:**

	•	Title: A concise and descriptive title for the issue.
	•	Description: A clear explanation of the issue or feature request.
	•	Steps to Reproduce (for bugs): A list of steps to replicate the issue.
	•	Expected Behavior: What should happen if the issue is resolved.
	•	Screenshots or Logs: Space for attaching relevant images or logs.
	•	Environment Details: Information such as OS, browser, or software versions.
	•	Additional Context: Any other details that might help resolve the issue.

**The template file should be named ISSUE_TEMPLATE.md and placed in the .github folder.**

**Comment by Iwueseiter** [comment]
I'm a frontend/smart contract developer and a technical writer.
Here are links to comprehensive docs I've written and have been merged Flex-NFT-Marketplace/Flex-Marketplace-Contract#107, https://github.com/cairo-book/cairo-book/pull/1019, https://github.com/horuslabsio/tokenbound-contract-docs/pull/12, https://github.com/sivicstudio/starkludo/pull/102, https://hackmd.io/@-__sK8xkRjuXHkFZQLyYXg/HkLcMImM1l.

**Comment by nov0ax** [comment]
Could I take on this issue? I've worked on github templates in the past and would like to be part of this amazing project as part of the Dojo Coding CR comunity.

**Comment by Akshola00** [comment]
Is it okay if I take this?

**Comment by anonfedora** [comment]
I'm Eleazar, a fullstack Blockchain developer, will Create a directory: In the root directory of the repository, create a new directory called PULL_REQUEST_TEMPLATE and a template file: Inside the PULL_REQUEST_TEMPLATE directory.
ETA: 24hours

**Comment by Kom02** [comment]
Hi, My name is Kevin Obando, a full stack junior developer with 2 years of experience from Costa Rica. I am starting in this community and I want to help in this project.

**Comment by jsandinoDev** [comment]
Hi  I'm a full-stack developer from Costa Rica and member of Dojo coding. I've worked on projects using React, Solidity, Cairo, and blockchain tools. My skills in both front-end and back-end development allow me to build scalable and secure solutions for web3 ecosystems.
I would love to work on this! I already worked in others projects like shinigami creating files like this

**Comment by Benjtalkshow** [comment]
Mind if I take this issue?

**Comment by pheobeayo** [comment]
Can I attempt this issue?
I am a Web3 front-end developer skilled in technical documentation and software development. I greatly understand technologies like JavaScript, Typescript, Cairo, Rust and Solidity. I have contributed successfully to open-source projects like Stark Quest and Speedrun scaffold-stark.

How I plan to tackle the issue
-Write a well-structured template containing the needed information using the correct references for a PR template outlining the parts needed as instructed.
- Create a Pull Request (PR)
- Request for a Review
- Make changes based on the Review of the PR.

**Comment by ShantelPeters** [comment]
I'd like to handle this task.

**Comment by Bran18** [comment]
Could I take over this issue?

**Comment by Bran18** [comment]
Hello there, I’m Brandon, part of the ⛩️ Dojo Coding community, and I would love to contribute to this project! 🚀 This might be my first contribution here, and I would be very happy for it to be on your project. I’ve always known this one would be something special guys.

I’ve collaborated on a couple of issue guides for our Open Source products at Bitcash.app and the related projects, and I believe I can genuinely help by creating a clear and effective guide to guide and track new collaborators—something I’m sure you’ll have plenty of for sure.

Lmk if I can start working on it.  Here’s my GitHub profile: GitHub: https://github.com/Bran18 and my OnlyDust profile: https://app.onlydust.com/u/Bran18. 

BTW tks for taking the time 🙏

**Comment by EmmanuelAR** [comment]
Can I contribute to this one? I will create the template, also im manteiner too so i have experience, Dojo coding member too!

**Comment by derianrddev** [comment]
Hello, my name is Derian Rodríguez. I am a passionate software engineer with over one year of experience, actively contributing to open-source projects through OnlyDust. My experience includes full-stack development with a focus on backend, frontend, and web3 development using Starknet and Cairo. Additionally, I am part of the Dojo Coding community. I would follow all the guidelines and instructions to get exactly what you want. I would love to contribute and support the development of this project.

**Comment by sasasamaes** [comment]
Thank you for your enthusiasm in contributing to our project. 
Wishing you great success as you take on this task.

Any questions you may have, please let us know.
Assigned @josephpdf 🫡
