### ISSUE TITLE
Fetch Escrow by Engagement ID in Android App

### ISSUE THREAD

**Issue by sasasamaes** [Crypto-Jaguars/Revolutionary_Farmers#7]
Implement functionality in the Android app to retrieve escrow details using the engagement ID from the Trustless Work API.

**TASKS:**

## 1.	API Integration:
	•	Utilize the endpoint: [GET Escrow by Engagement ID](https://docs.trustlesswork.com/trustless-work/api-reference/escrows/get-escrow-by-engagement-id).
	•	Handle required parameters to make the API request.
## 2.	Response Handling:
	•	Parse and display relevant data from the API response in the app.
	•	Handle potential errors (e.g., invalid engagement ID, network issues).
## 3.	UI Implementation:
	•	Create or update UI elements to input the engagement ID and display escrow details.
	•	Ensure the interface is intuitive and user-friendly.
## 4.	Testing:
	•	Verify the functionality works as expected under different scenarios (valid/invalid engagement IDs, no network).

**Mockups / References**

**Form get egegement ID**
<img width="516" alt="Screenshot 2024-11-27 at 10 59 08 AM" src="https://github.com/user-attachments/assets/e76b07e3-18ef-483e-b00d-1aa9753c7c18">

**Info Engagement**
<img width="312" alt="Screenshot 2024-11-27 at 10 58 09 AM" src="https://github.com/user-attachments/assets/6be8f1ae-405f-44a9-81d6-ab6bc4f01ec1">

**Refer to the figma design:**
[FIGMA DESIGN Form Find Escrow](https://www.figma.com/design/okdNMG3dW4UFcKUSikrs6e/Revolutionary-Farmers?node-id=176-9051&t=pDfhvIMZyooGfkyL-4)

[FIGMA DESIGN Info Engagement ID](https://www.figma.com/design/okdNMG3dW4UFcKUSikrs6e/Revolutionary-Farmers?node-id=176-8930&t=pDfhvIMZyooGfkyL-4)

## Expected Outcome:

The Android app should allow users to fetch and view escrow details by providing an engagement ID, ensuring smooth integration with the Trustless Work API.

**Comment by mimisavage** [comment]
I’d like to help with this.

**Comment by Hoossayn** [comment]
Let me handle this issue 😎

**Comment by ShantelPeters** [comment]
Can I attempt this issue?

**Comment by Ekene001** [comment]
Hi, I'm Ekene, a frontend and blockchain developer, and I’m new to the OnlyDust platform. This is my first time contributing to this repository, and I’m excited about the opportunity to collaborate and bring my skills to the table. 

To tackle this task:

I’ll integrate the GET Escrow by Engagement ID API, making sure all the necessary parameters are handled correctly.
Once the API response is received, I’ll parse it to display the escrow details and handle any errors, like invalid IDs or network issues, gracefully.
I’ll update the app’s UI to include a user-friendly way for users to input the engagement ID and view the escrow details.
Then,  I’ll thoroughly test everything to make sure it works smoothly in different scenarios.

**Comment by KoxyG** [comment]
Hi my name is koxy. I am a blockchain developer with experience with typescript, rust and solidity. 

I also have experience in integrating apis. I would love to work on this, can you pls assign me to this?

**Comment by blessingbytes** [comment]
pls , i would love to tackle this issue

**Comment by Supa-mega** [comment]
Can I handle this task?

**Comment by ooochoche** [comment]
I have gone through the description and I can resolve all the task stated and meet the expected outcomes

**Comment by Rayguti** [comment]
Description:
Implement functionality in the Android app to fetch and display escrow details using the engagement ID from the Trustless Work API.

Why I’m Interested:
I have a strong background in software development, including API integration, Android development, and creating user-friendly interfaces. My experience with handling network requests, error management, and building intuitive UI aligns well with the requirements of this task. I am confident that I can deliver a solution that not only integrates seamlessly with the Trustless Work API but also enhances the user experience.

Proposed Solution:

    API Integration:
        Use the provided GET Escrow by Engagement ID endpoint to retrieve escrow details.
        Implement the HTTP client (e.g., Retrofit) to handle API requests and responses.

    Response Handling:
        Parse the API response into structured models.
        Implement error handling for invalid IDs, network issues, and unexpected server responses.
        Provide clear user feedback for errors.

    UI Implementation:
        Add an input field for the engagement ID and a button to trigger the API call.
        Create a results section to display escrow details in a user-friendly format.
        Use modern UI frameworks to ensure responsiveness and visual appeal.

    Testing:
        Test the feature with valid and invalid engagement IDs.
        Simulate network issues to verify the app handles offline scenarios gracefully.
        Write unit and UI tests to ensure functionality and reliability.

Outcome:
The app will enable users to input an engagement ID and view the corresponding escrow details, providing a seamless integration with the Trustless Work API and improving overall usability.

**Comment by chigozzdevv** [comment]
Could I take on this issue? I'm a Flutter and Java developer.

**Comment by Shalomnze** [comment]
Can I jump on this task?

**Comment by CEOliam** [comment]
Can I start working on this?

**Comment by IsaacHerreraAguilar** [comment]
Hi, I'm Isaac Herrera. I'm a FrontEnd developer with 2 years of experience. I have a little bit of experience in Android and I could help with this issue. I'm very interested. My proposal would be to make a Fetch method with the entered data (engagement ID and contract ID) and display the relevant information with a clean and friendly interface.

**Comment by IsaacHerreraAguilar** [comment]
Hi, I'm Isaac Herrera. I'm a FrontEnd developer with 2 years of experience. I have a little bit of experience in Android and I could help with this issue. I'm very interested. My proposal would be to make a Fetch method with the entered data (engagement ID and contract ID) and display the relevant information with a clean and friendly interface.
