### ISSUE TITLE
Implement Fund Escrow Functionality in Android App

### ISSUE THREAD

**Issue by sasasamaes** [Crypto-Jaguars/Revolutionary_Farmers#8]
Add functionality to fund an escrow directly from the Android app using the Trustless Work API.

**TASKS:**

## 1.	API Integration:
	•	Utilize the endpoint: [Fund Escrow API](https://docs.trustlesswork.com/trustless-work/api-reference/escrows/fund-escrow).
	•	Ensure the request includes all required parameters (e.g., escrow ID, funding amount, etc.).
	•	Implement secure token handling for API authentication.
## 2.	UI Implementation:
	•	Design a user-friendly interface for funding escrows.
	•	Include input fields for necessary details (e.g., escrow ID, amount).
	•	Provide confirmation dialogs before submitting the transaction.
## 3.	Response Handling:
	•	Parse the API response to confirm success or handle errors.
	•	Display appropriate success or error messages to the user.
## 4.	Error Handling:
	•	Handle common errors like insufficient balance, invalid escrow ID, or network issues.
## 5.	Testing:
	•	Validate the feature under different scenarios (valid/invalid inputs, API failures, etc.).

## Expected Outcome:

Users should be able to fund an escrow in the app securely and efficiently, with clear feedback on the transaction status.

**Comment by BrunoAmbricca** [comment]
I would like to work on this issue

**Comment by JoE11-y** [comment]
Mind if I take this issue?

**Comment by ShantelPeters** [comment]
Could I be assigned to this?

**Comment by evgongora** [comment]
Hey! My name is Erick, I'm part of the Dojo Coding community.

I'm a software engineering student working on fullstack web development, I have experience building different views with responsive layout. This will be my first time working on Android but I'll make sure to deliver a good PR.
I have experience as a contributor and as a maintainer.
You can check my work here: https://app.onlydust.com/u/evgongora

Let me know if I can hop on this, I would love to contribute to this project.
